#Devlopment Environment Configuration
environment:
  name: "dev"
  aws_region: "us-east-1"
  terraform_version: "1.5.0"

#Deployment order for rolling deployment
deployment_modules:
  - name: "networking"
    path: "modules/networking"
    critical: true 
  - name: "security"
    path: "modules/security"
    critical: true 
  - name: "storage"
    path: "modules/storage"
    critical: false
  - name: "database"
    path: "modules/database" 
    critical: true
  - name: "compute"
    path: "modules/compute"
    critical: true
  - name: "monitoring"
    path: "modules/monitoring"
    critical: false
